# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TagListViewDemo' do

end

target 'TagListViewTests' do
  pod 'Expecta+Snapshots'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock', '~> 3.1.2'
end

inhibit_all_warnings!
